### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by vadim2404** [jaytaph/SFConsole#1]
https://github.com/KnpLabs/symfony2-autocomplete

**Comment by elmariachi111** [comment]
but this one works with bash only :+1: 

~~btw: I'd like to shorten "app/console" to "sf", tried with~~
~~alias sf="app/console"~~
~~complete -F _complete_sf2_app_console sf~~
~~but that only gives: $/my/project/root > sf [tab] -> sf: command not found. Got that working once but forgot how to do it~~

got it from the "duplicate" git (https://github.com/KnpLabs/symfony2-autocomplete/issues/12) :

> created a Bash Script sf in /usr/local/bin/ with the following content:
> 
> ``` sh
> #!/bin/bash
> php `pwd`/app/console "$@"
> ```

**Comment by jaytaph** [comment]
Yeah, I saw the knp autocomplete as well, but only after creating this one. Pretty much the same idea, but I don't really like the fact it uses php calls internally.  This version definitely isn't fool-proof, but it gets the job done.
